spring:
  datasource:
    "https://mvnrepository.com/search?q=": jdbc:h2:file:/data/demo/springbaza
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console.enabled: true
